Sunbird-Lern/sunbird-utils

- common-util/pom.xml
- common-util/src/main/java/org/sunbird/common/models/util/ActorUtility.java
- common-util/src/main/java/org/sunbird/common/models/util/HttpUtil.java
- common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- common-util/src/main/java/org/sunbird/common/models/util/ProjectUtil.java
- common-util/src/main/java/org/sunbird/common/models/util/Slug.java
- common-util/src/main/java/org/sunbird/common/models/util/azure/AzureFileUtility.java
- common-util/src/main/java/org/sunbird/common/models/util/mail/SendMail.java
- common-util/src/main/java/org/sunbird/services/sso/impl/KeyCloakServiceImpl.java
- common-util/src/main/resources/application.conf
- common-util/src/main/resources/externalresource.properties
- elasticsearch-util/src/main/java/org/sunbird/helper/ElasticSearchMapping.java
- elasticsearch-util/src/main/java/org/sunbird/helper/ElasticSearchQueryBuilder.java
Change related to running actors locally/remotely/in mixed mode based on configuration
> Issue #SB-219 feat:local actor feature

- common-util/src/main/resources/externalresource.properties
- kafka-client/.gitignore
- kafka-client/pom.xml
- kafka-client/src/main/java/org/sunbird/kafka/client/KafkaClient.java
adding new module as kafka-client , current that client is used inside telemetry service.
> Issues #SB-766 feat: creating separate code base for kafka client

- actor-core/src/main/java/org/sunbird/actor/core/BaseActor.java
- cassandra-dac/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java
Issue # SB-3955 Development - Org bulk upload not working.
> Issue # SB-3955 Development :Org bulk upload not working.

- cassandra-dac/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java
Issue #  3955 - Org bulk upload not working.
> Org refactoring

- common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- common-util/src/main/java/org/sunbird/telemetry/util/TelemetryDispatcherSunbirdLMS.java
- common-util/src/main/resources/externalresource.properties
changes for making telemetry call to sunbird telemetry service.
> Telemetry call routing

- common-util/src/main/java/org/sunbird/common/models/util/ProjectUtil.java
- common-util/src/test/java/org/sunbird/common/models/util/ProjectUtilTest.java
> Issues #SB-3684 fix: adding new method to calculate date range

- common-service/src/main/java/org/sunbird/controllers/BaseController.java
- common-service/src/main/java/org/sunbird/controllers/mapper/RequestMapper.java
- common-util/src/main/java/org/sunbird/telemetry/util/TelemetryConstant.java
Issue # SB-4221 Development :Org micro service refactoring.
> Issue # SB-4221 Development :Org micro service refactoring.

- common-util/src/main/java/org/sunbird/telemetry/util/TelemetryDispatcherSunbirdLMS.java
- elasticsearch-util/src/main/java/org/sunbird/common/ElasticSearchUtil.java
removing the logs which is printing huge data.
> Util log cleanup

- common-service/src/main/java/org/sunbird/global/BaseGlobal.java
- common-service/src/main/java/org/sunbird/global/ServiceBaseGlobal.java
- common-service/src/main/java/org/sunbird/util/authentication/AuthenticationHelper.java
- common-service/src/main/java/org/sunbird/util/authentication/RequestInterceptor.java
- common-util/src/main/java/org/sunbird/common/request/HeaderParam.java
Issue # SB-4221 Development User org refactor common service .
> Issue # SB-4221 Development User org refactor common service

- common-util/src/main/resources/externalresource.properties
> Issues #SB-4636 fix: chnages telemetry api url

- common-util/src/main/java/org/sunbird/common/models/util/BadgingJsonKey.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
Issue # SB - 2994 - Badging Framewrok - Create Assertion should validate the rootOrg .
> Issue # SB - 2994 - Badging Framewrok - Create Assertion should validate the rootOrg .

- common-util/src/main/java/org/sunbird/common/models/util/DbConstant.java
Issue # SB- 2944 : Relaese 1.8 bug fixes
> Issue # SB- 2944 : Relaese 1.8 bug fixes

- common-util/src/main/java/org/sunbird/common/models/util/ProjectUtil.java
Issue #SB-2868 fix: review comment
> Platform_APIs_ERROR_500

- cassandra-migration/src/main/resources/db/migration/cassandra/V1.12_cassandra.cql
> Issues #SB-4925 feat: cql changes for hashtag

- common-util/src/main/java/org/sunbird/common/request/LearnerStateRequestValidator.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
Bug fix BS- 4805 : View Course batch status.
> Bug fix BS- 4805 : View Course batch status.

- common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- common-util/src/main/java/org/sunbird/common/models/util/ProjectUtil.java
- common-util/src/main/resources/externalresource.properties
- common-util/src/main/resources/welcomeSmsTemplate.vm
- common-util/src/test/java/org/sunbird/common/models/util/ProjectUtilTest.java
Issue # SB-4115 Development : Sunbird On-boarding SMS : For Sunbird user on boarding why we are mentioning Diksha app.
> Issue # SB-4115 Development : Sunbird On-boarding SMS .

- common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java
User Role Assign API change for allowing removal of existing roles
> Issue #SB-5226 fix: Replace user-roles changes

- common-util/src/main/java/org/sunbird/common/request/RequestValidator.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
#SB-2733 fix: Course batch Update
> #SB-2733 fix: Course batch Update

- common-util/src/main/java/org/sunbird/common/models/util/BadgingJsonKey.java
- common-util/src/main/java/org/sunbird/common/request/BaseRequestValidator.java
Changes for badging (Issuer, badgeclass, assertion) error message
> Issues #SB-2425

- common-util/src/main/java/org/sunbird/common/models/util/ActorOperations.java
- common-util/src/main/java/org/sunbird/common/request/RequestValidator.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
- models/src/main/java/org/sunbird/models/course/batch/CourseBatch.java
- models/src/main/java/org/sunbird/models/user/courses/UserCourses.java
> Issue #SB-5958 feat: Unenroll user from Course Batch API

- cassandra-dac/src/test/java/org/sunbird/cassandra/CassandraStandaloneTest.java
- cassandra-dac/src/test/java/org/sunbird/cassandra/CassandraTest.java
- common-util/pom.xml
- common-util/src/test/java/org/sunbird/common/models/AppTest.java
- common-util/src/test/java/org/sunbird/common/models/util/ProjectUtilTest.java
- common-util/src/test/java/org/sunbird/common/models/util/azure/AzureServiceFactoryTest.java
- common-util/src/test/java/org/sunbird/common/models/util/fcm/FCMNotificationTest.java
- common-util/src/test/java/org/sunbird/common/request/CommonRequestValidatorTest.java
- common-util/src/test/java/org/sunbird/common/request/PageSectionValidatorTest.java
- common-util/src/test/java/org/sunbird/common/request/UserRequestValidatorTest.java
- common-util/src/test/java/org/sunbird/services/sso/impl/KeyCloakRsaKeyFetcherTest.java
- common-util/src/test/java/org/sunbird/services/sso/impl/KeyCloakServiceImplTest.java
- elasticsearch-util/pom.xml
- elasticsearch-util/src/test/java/org/sunbird/common/ElasticSearchUtilTest.java
- request-validator/src/test/java/org/sunbird/validator/location/LocationRequestValidatorTest.java
- sunbird-notification/src/test/java/org/sunbird/notification/sms/Message91GetSMSTest.java
- sunbird-notification/src/test/java/org/sunbird/notification/sms/Message91Test.java
Merge request along with all the requestsed changes
> Merging the changes for elast-search-unit by switching to latest branch.

- sunbird-notification/pom.xml
- sunbird-notification/src/test/java/org/sunbird/notification/sms/BaseMessageTest.java
- sunbird-notification/src/test/java/org/sunbird/notification/sms/Message91GetSMSTest.java
- sunbird-notification/src/test/java/org/sunbird/notification/sms/Message91Test.java
required methods, and removing external dependency of connecting  to
actual gateway.
> commit the changes for fixing notificaiton module by mocking http client

- common-util/src/main/java/org/sunbird/services/sso/impl/KeyCloakRsaKeyFetcher.java
- common-util/src/main/java/org/sunbird/services/sso/impl/KeyCloakServiceImpl.java
url updated
old url was like http://example.com/auth+ "/auth/realms/" +realms+  "/protocol/openid-connect/certs"
updated url    http://example.com/auth + "/realms/" + realm + "/protocol/openid-connect/certs"
> Keycloak issue for fetching public key 

- common-util/src/main/java/org/sunbird/common/request/UserProfileRequestValidator.java
- common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java
- common-util/src/test/java/org/sunbird/common/request/CommonRequestValidatorTest.java
- common-util/src/test/java/org/sunbird/common/request/UserProfileRequestValidatorTest.java
- common-util/src/test/java/org/sunbird/common/request/UserRequestValidatorTest.java
discarding other changes from unit-test done earlier for test-case
re-factoring.
> SB-8241 - changes for curernt branch.

- common-util/src/main/java/org/sunbird/common/exception/ProjectCommonException.java
Add throwUnauthorizedErrorException in ProjectCommonException
> Issue #SB-8012 feat: Add throwUnauthorizedErrorException

- common-util/src/main/java/org/sunbird/common/exception/ProjectCommonException.java
Unauthorized Error fixes in ProjectCommonException
> Issue #SB-8012 feat: Unauthorized fixes

- models/src/main/java/org/sunbird/models/user/org/UserOrg.java
setting property field to match with user-org columns
> setting property field to match with user-org columns

- common-util/src/main/java/org/sunbird/common/request/UserProfileRequestValidator.java
null check in case any one of public or private field is missing
> null check in case any one of public or private field is missing

- common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java
> Changes in the handdling frameworkrequest

- common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
Added error for unsupported framework field in request body
> Added error for unsupported framework field in request

- common-util/src/main/resources/externalresource.properties
> User update with framework

- common-util/src/test/java/org/sunbird/common/models/util/ProjectUtilTest.java
- common-util/src/test/java/org/sunbird/common/request/OrgValidatorTest.java
- common-util/src/test/java/org/sunbird/common/request/UserRequestValidatorTest.java
- common-util/src/test/java/org/sunbird/services/sso/impl/KeyCloakServiceImplTest.java
> ignore tests

- common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
> Issue #SB-9147 feat: added queryString to jsonkey

- common-util/pom.xml
Merging utils with release-1.12
> Issue #SB-0000 fix: Fix for AbstractMethodError in UriBuilder

- actor-core/pom.xml
- actor-util/pom.xml
- common-util/pom.xml
- content-util/pom.xml
- kafka-client/pom.xml
- request-validator/pom.xml
akka-actor_2.11
also -updated relevant jars to compatible versions
> Upgrading the jar where vulnerability is reported as per github.

- common-util/src/main/java/org/sunbird/common/models/util/ActorOperations.java
> new actor operation

- common-util/src/main/java/org/sunbird/common/models/util/ActorOperations.java
- common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
Added new actor operation and otp in json key
> Otp verification

- common-util/src/main/resources/cassandratablecolumn.properties
> changes for phone verified and email verified mapping for cassandra

- common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- common-util/src/main/resources/externalresource.properties
Added constants for max phone number alowed
> Encryption

- cassandra-migration/src/main/resources/db/migration/cassandra/V1.53_cassandra.cql
- common-util/src/main/java/org/sunbird/common/models/util/BadgingActorOperations.java
- common-util/src/main/java/org/sunbird/common/models/util/BadgingJsonKey.java
- common-util/src/main/java/org/sunbird/common/models/util/ProjectUtil.java
Util changes for badge association
> Badge association

- common-util/src/main/java/org/sunbird/common/models/util/ActorOperations.java
- common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- common-util/src/main/java/org/sunbird/common/models/util/ProjectUtil.java
- common-util/src/main/java/org/sunbird/common/request/RequestValidator.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
- yaml-generator/.project
- yaml-generator/.pydevproject
- yaml-generator/yaml/config.json
- yaml-generator/yaml/config.yaml
- yaml-generator/yaml/generator.py
- yaml-generator/yaml/template/header.txt
- yaml-generator/yaml/template/httpHeaderAccept.txt
- yaml-generator/yaml/template/httpHeaderAuthorization.txt
- yaml-generator/yaml/template/httpHeaderContentType.txt
- yaml-generator/yaml/template/httpHeaderId.txt
- yaml-generator/yaml/template/httpHeaderTs.txt
- yaml-generator/yaml/template/httpHeaderXAuthenticatedUserToken.txt
- yaml-generator/yaml/template/httpHeaderXAuthenticatedUserid.txt
- yaml-generator/yaml/template/httpHeaderXConsumerId.txt
- yaml-generator/yaml/template/httpHeaderXDeviceId.txt
- yaml-generator/yaml/template/httpHeaderXMsgid.txt
> Issue #SB-0000 feat: Yaml Generator from JSON

- common-util/src/test/java/org/sunbird/common/models/util/ProjectUtilTest.java
> Project util test bug

- common-util/pom.xml
This reverts commit 36fe43e6dd7d21342317fcf3205989bd895cb8db. for other flow verification
> Revert "jar correction"

- common-util/pom.xml
This reverts commit 5e634385ee2e2eeeda9a61f9da9e274f9041835d.
> Revert "Revert "jar correction""

- common-util/pom.xml
- common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- content-util/src/main/java/org/sunbird/content/util/TextBookTocUtil.java
- elasticsearch-util/src/main/java/org/sunbird/common/ElasticSearchUtil.java
- elasticsearch-util/src/main/java/org/sunbird/dto/SearchDTO.java
Es changes for contains search
> Release 1.14 sp3

- common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java
Utility for health service improvement
> Health service

- common-util/src/main/resources/externalresource.properties
> Issue #SB=10876 feat:Added after dev testing

- models/src/main/java/org/sunbird/models/user/User.java
Added mask email and maskPhone in User model class
> Issue #SB-11317 feat: MaskEmail and MaskPhone from response

- cassandra-trigger/src/main/java/org/sunbird/cassandra/Trigger.java
- cassandra-trigger/src/main/java/org/sunbird/common/audit/AuditUtil.java
> Issue #SB-11593 feat: Support for bulk insert

- cassandra-migration/src/main/resources/db/migration/cassandra/V1.64_cassandra.cql
Cql query for trigger location
> Trigger on table location

- cassandra-dac/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java
'Read specific column from all rows' support
> Enhance CassandraImpl Support

- Jenkinsfile.trigger
This addition is to build the cassandra trigger jar file
> Added the cassandra trigger jenkinsfile

- cache-util/src/main/java/org/sunbird/cache/CacheFactory.java
- elasticsearch-util/src/main/java/org/sunbird/helper/ConnectionManager.java
> Issues #SB-00 fix: chnages for es and redis netty jar

- cassandra-migration/src/main/resources/db/migration/cassandra/V1.64_cassandra.cql
changes for making job user course table update as sync from Async. and adding new columns in user-courses table to identify operation lack.
> Issues #SB-12256 fix: adding one column in user_courses table

- common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
Added signupType in jsonKey file
> Added json key for signup type

- common-util/src/main/resources/externalresource.properties
> SB-12454: TOC upload issue fix

- sunbird-es-utils/src/main/java/org/sunbird/common/ElasticSearchHelper.java
- sunbird-es-utils/src/main/java/org/sunbird/common/ElasticSearchRestHighImpl.java
<b>Ticket Ref: </b> [SC-1115](https://project-sunbird.atlassian.net/browse/SC-1115)
1: Change elasticsearch timeout to 5s from 30s.
2: since it should return blank empty map if response not found instead of returning timout exception
> SC-1115 Es Config and Promise Handling

- decryption-util/README.md
- decryption-util/src/main/java/org/sunbird/decryptionUtil/ExternalIdDecryption.java
- decryption-util/src/main/java/org/sunbird/decryptionUtil/RecordProcessor.java
- decryption-util/src/main/java/org/sunbird/decryptionUtil/connection/CassandraConnection.java
- decryption-util/src/main/java/org/sunbird/decryptionUtil/constants/EnvConstants.java
<b>Ticket Ref: [SB-13506](https://project-sunbird.atlassian.net/browse/SB-13506)</b>
1: previously Cassandra is supporting only 1 host now some changes have been made to support Cassandra with multiple hosts.
2: earlier the env for the host is cassandra_host is now renamed to sunbird_cassandra_host.
> SB-13506 ExternalId decryption script

- sunbird-es-utils/src/main/java/org/sunbird/common/ElasticSearchHelper.java
- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- sunbird-platform-core/common-util/src/main/resources/externalresource.properties
changes for es nested search and certificate properties
> changes for es nested search and certificate properties

- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
> Issue SB-14372 removed while merging, now added again

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.77_cassandra.cql
> Issue #SB-13498: Fixed table creation issue

- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
> Download Report API Response variable changes from URL to Url

- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- sunbird-platform-core/common-util/src/main/resources/externalresource.properties
> Issue #SB-14495 feat: Config changes for Course Progress report API changes to include assessment report.

- sunbird-cassandra-utils/src/main/java/org/sunbird/cassandraimpl/CassandraDACImpl.java
Reverts project-sunbird/sunbird-utils#647
> Revert "Issue#SC-1323 Added Query filtering"

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.77_cassandra.cql
- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.79_cassandra.cql
> Issue #SB-13498 : Changed datatype of score field from int to double

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.79_cassandra.cql
- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/RequestValidator.java
> Request Validator changes to make contents list as optional and Cassandra migration changes

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.79_cassandra.cql
> Issue #SB-13498 : added ets column to question udt type

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.79_cassandra.cql
> Issue #SB-13498 : issue fix added grand_total column

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.80_cassandra.cql
- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.81_cassandra.cql
> Issue #SB-13498 : Added the New cql files for branch conflict issue

- sunbird-platform-core/common-util/src/main/resources/externalresource.properties
Shadow user scheduler time changed to 1 AM every night
> Shadow user time changed

- sunbird-cassandra-utils/src/main/java/org/sunbird/cassandra/CassandraOperation.java
- sunbird-cassandra-utils/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java
Reverts project-sunbird/sunbird-utils#699
> Revert "SC-1387 "

- sunbird-platform-core/common-util/src/main/resources/externalresource.properties
chnages for telemetry version as per release.
> issue #SB-15723 fix: changes for telemetry version

- sunbird-platform-core/common-util/src/test/java/org/sunbird/common/request/OrgValidatorTest.java
Changes for Unit test.
couple of unit test was ignored and for some call of method was commented , so enabling all
> issue #SB-15791 fix:changes for unit test

- decryption-util/src/main/java/org/sunbird/decryptionUtil/RecordProcessor.java
- decryption-util/src/main/java/org/sunbird/decryptionUtil/constants/EnvConstants.java
- decryption-util/src/main/java/org/sunbird/decryptionUtil/tracker/RecordTracker.java
- decryption-util/src/main/java/org/sunbird/decryptionUtil/tracker/StatusTracker.java
1: Resolving merge conflicts of decryptionUtils
> Resolving merge conflicts for decryptionUtils

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.88_cassandra.cql
- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.89_cassandra.cql
Removing file 1.89 and chnages in 1.88
as 1.89 is not required, was duplicate of 1.88
> attemptCount changed to attemptedCount

- notification-sdk/src/test/java/org/sunbird/notification/sms/Message91Test.java
- sunbird-platform-core/common-util/src/test/java/org/sunbird/service/profile/ProfileCompletenessTest.java
ignoring failing testcase temporarily
> ignoring failing testcase

- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
changes for reset password error message only.
> issue #SB-1319 fix: changes for showing error message

- sunbird-platform-core/common-util/src/main/resources/OTPSMSTemplate.vm
- sunbird-platform-core/common-util/src/main/resources/acceptFlagMailTemplate.vm
- sunbird-platform-core/common-util/src/main/resources/contentFlaggedMailTemplate.vm
- sunbird-platform-core/common-util/src/main/resources/contentReviewMailTemplate.vm
- sunbird-platform-core/common-util/src/main/resources/emailtemplate.vm
- sunbird-platform-core/common-util/src/main/resources/forgotPasswordWithOTP.vm
- sunbird-platform-core/common-util/src/main/resources/forgotpassword.vm
- sunbird-platform-core/common-util/src/main/resources/publishContentMailTemplate.vm
- sunbird-platform-core/common-util/src/main/resources/rejectContentMailTemplate.vm
- sunbird-platform-core/common-util/src/main/resources/rejectFlagMailTemplate.vm
- sunbird-platform-core/common-util/src/main/resources/unlistedPublishContentMailTemplate.vm
- sunbird-platform-core/common-util/src/main/resources/welcomeMailTemplate.vm
- sunbird-platform-core/common-util/src/main/resources/welcomeSmsTemplate.vm
This reverts commit fe9d62c91761f8472d27063f6512f7143ebeb0de.
> Revert "Issue #SC-1467 fix: removing all velocity template file (#764)"

- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java
- sunbird-platform-core/common-util/src/test/java/org/sunbird/common/request/UserRequestValidatorTest.java
Adding email and phone format verification during signup.
> issue #SB-00 fix: changes for phone and email validation

- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java
- sunbird-platform-core/common-util/src/test/java/org/sunbird/common/request/UserRequestValidatorTest.java
in signup api adding email and phone syntax verification.
> issue #SB-00 fix: changes for phone and email verification

- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/KeyCloakConnectionProvider.java
- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/KeycloakRequiredActionLinkUtil.java
Changes to accept  client-secret
> issue #SC-1635 fix: changes for client secret

- sunbird-platform-core/actor-util/src/main/java/org/sunbird/actorutil/systemsettings/impl/SystemSettingClientImpl.java
- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/KeyCloakConnectionProvider.java
- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/KeycloakRequiredActionLinkUtil.java
PR from 2.7.0 to 2.8.0 
changes for client secret
chnages for system settings
> Release 2.7.0

- sunbird-platform-core/common-util/pom.xml
- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/CloudStorageUtil.java
- sunbird-platform-core/common-util/src/test/java/org/sunbird/common/util/CloudStorageUtilTest.java
1: Upgraded Cloud-sdk to version 1.2.5 to 1.2.1
2: included org.slf4j dependency
> SC-1653 Update cloud-sdk lib version

- sunbird-es-utils/src/main/resources/reindexing/README.md
- sunbird-es-utils/src/main/resources/reindexing/indices/certreg_indices.json
- sunbird-es-utils/src/main/resources/reindexing/mappings/certreg_mappings.json
- sunbird-es-utils/src/main/resources/reindexing/reindex.sh
**Ticket Ref:** [SB-17927](https://project-sunbird.atlassian.net/browse/SB-17927?filter=10743)
1: Script Added to reindex ES indices.
2: view README.md [here](https://github.com/anmol2302/sunbird-utils/blob/49a2646b531b2e85d92ee285c0a82a79a7799c82/sunbird-es-utils/src/main/resources/reindexing/README.md)
> Issue#SB-17927(ES reindexing script added to sunbird-utils)

- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java
- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
- sunbird-platform-core/common-util/src/main/resources/externalresource.properties
For gracefull shutdown of play server
https://www.playframework.com/documentation/2.8.x/Shutdown
> Issue #SC-1722 feat: handling SIGTERM signal for gracefull shutdown

- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java
- sunbird-platform-core/common-util/src/main/resources/externalresource.properties
- sunbird-platform-core/common-util/src/test/java/org/sunbird/common/request/UserRequestValidatorTest.java
Changed password regexp according to ticket and tests added.
This password for directly set for a user in the KC console and found to be accepted.
> SB-18949 Change password regexp

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.98_cassandra.cql
Adding role and rolegroup as 'COURSE_CREATOR'
> SH-46 C2 - Create a role course creator

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.98_cassandra.cql
Adding verifyPhoneOtpTemplateWard to email_templates
> SH-55 Create a verifyPhoneTemplate

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.98_cassandra.cql
Merging Issue #SB-18298 feat: Added dynamicFilters in page section from 2.10.00
> #SB-18298 feat: Added dynamicFilters in page section 

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.100_cassandra.cql
- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.98_cassandra.cql
- sunbird-es-utils/src/main/resources/indices/user.json
- sunbird-es-utils/src/main/resources/mappings/user-mapping.json
Adding managedBy and accessCode to user - cassandra and es changes
> SH-111 PU - Schema changes for user

- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java
- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java
- sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
> SH-135 Disallow managedBy to be updated

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.101_cassandra.cql
- sunbird-platform-core/common-util/src/main/resources/cassandratablecolumn.properties
changes column activities datatype from map<text,tex> ->  set<frozen <map<text,text>>>
> SH-392: updated the dataType of activities in group table

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.101_cassandra.cql
- sunbird-platform-core/common-util/src/main/resources/cassandratablecolumn.properties
reason: set of frozen map type[activities] saving null while updating column
> SH-392: changed datatype of column activities in group table

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.101_cassandra.cql
Cassendra table creation for Groups
Adding status column to usr_external_identity
> SH-392 Add index on status column

- Jenkinsfile.decrypt
Jenkins job will build and run this job running migration script in externalId-migration-util
> SC-1852 Script change for jenkins job

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.106_cassandra.cql
Reverts project-sunbird/sunbird-utils#937
> Revert "SC-1904: Added new column qrCodeUrl in cert-registry table"

- externalId-migration-util/src/main/java/org/sunbird/migration/CassandraHelper.java
- externalId-migration-util/src/main/java/org/sunbird/migration/RecordProcessor.java
Prod data store channel in upper case so checking for upper if original provider is in lowercase as presently available in prod data for mp
> SC-1878 Checking for channel in upper case

- externalId-migration-util/src/main/java/org/sunbird/migration/RecordProcessor.java
Cg state contains upper + lower case.hence fixing to support any case.
> SC-1990 fix case insensitive issue with channel

- db_data_scripts/scripts/alter_user_feed_script.sh
- db_data_scripts/scripts/alter_user_feed_table.cql
- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.109_cassandra.cql
Refactoring the user_feed table and migrating the data.
The steps will be configured and runned in jenkins job, first table refactor then moving data to same table.
The following script will be configured in the Jenkins job
http://10.20.0.14:8080/jenkins/job/Deploy/job/dev/job/Core/job/CassandraDBUpdate/
> SC-2019 Refactoring the user_feed table and migrating the table data

- user-declaration-util/src/main/java/org/sunbird/migration/RecordProcessor.java
Update status of user declarations from null to SUBMITTED
Update status PENDING to SUBMITTED
> SB-20930 Change PENDING to SUBMITTED

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.111_cassandra.cql
> SB-20957 Adding new column allTncAccepted and Visited column in the user and group_member table respectively

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.117_cassandra.cql
User table schema changes (SC-2184)
> SC-2223 table schema changes for restructuring location and usertype

- notification-sdk/src/test/java/org/sunbird/notification/sms/Message91Test.java
- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.120_cassandra.cql
- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.121_cassandra.cql
- sunbird-notification/src/test/java/org/sunbird/notification/sms/Message91Test.java
> Release 3.9.0

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.132_cassandra.cql
To support delete and update of the both version format, we need a mapping table
> SB-26762: create version mapping table

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.144_cassandra.cql
Schema changed
sunbird.user
sunbird.organisation 
sunbird.organisation
sunbird.organisation
> Modification in sunbird schemas

- sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/sunbird_programs/V1.1_cassandra.cql
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/LR-285" title="LR-285" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />LR-285</a>  User detail data for programs
</td></table>
<br />
> LR-285 Add Create Keyspace & Table
